In [2]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [4]:
#!pip install deepchem

In [5]:
import deepchem as dc
import numpy as np

In [6]:
tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21()

RDKit WARNING: [13:26:34] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [13:27:58] WARNING: not removing hydrogen atom without neighbors


In [10]:
# tox21_tasks

In [14]:
# tox21_datasets

In [15]:
train_dataset, valid_dataset, test_dataset = tox21_datasets

In [19]:
train_dataset.X.shape, valid_dataset.X.shape, test_dataset.X.shape

((6264, 1024), (783, 1024), (784, 1024))

In [26]:
train_dataset.y.shape, valid_dataset.y.shape, test_dataset.y.shape

((6264, 12), (783, 12), (784, 12))

In [28]:
train_dataset.w.shape

(6264, 12)

In [31]:
train_dataset.w[0]

array([1.04502242, 1.03632599, 1.12502653, 1.04541485, 1.14607755,
       1.05621135, 1.02555168, 1.17267917, 1.03538545, 1.05576503,
       1.17464996, 1.05288369])

In [44]:
train_dataset.w[4]

array([1.04502242, 1.03632599, 1.12502653, 1.04541485, 1.14607755,
       1.05621135, 1.02555168, 1.17267917, 1.03538545, 1.05576503,
       1.17464996, 1.05288369])

In [32]:
train_dataset.y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
tox21_tasks

['NR-AR',
 'NR-AR-LBD',
 'NR-AhR',
 'NR-Aromatase',
 'NR-ER',
 'NR-ER-LBD',
 'NR-PPAR-gamma',
 'SR-ARE',
 'SR-ATAD5',
 'SR-HSE',
 'SR-MMP',
 'SR-p53']

In [38]:
train_dataset.X[0]

(1024,)

In [40]:
train_dataset.ids[0]

'CC(O)(P(=O)(O)O)P(=O)(O)O'

In [45]:
transformers

In [46]:
help(dc.models.MultitaskClassifier)

Help on class MultitaskClassifier in module deepchem.models.fcnet:

class MultitaskClassifier(deepchem.models.keras_model.KerasModel)
 |  MultitaskClassifier(n_tasks: int, n_features: int, layer_sizes: Sequence[int] = [1000], weight_init_stddevs: Union[float, Sequence[float]] = 0.02, bias_init_consts: Union[float, Sequence[float]] = 1.0, weight_decay_penalty: float = 0.0, weight_decay_penalty_type: str = 'l2', dropouts: Union[float, Sequence[float]] = 0.5, activation_fns: Union[Callable, str, Sequence[Union[Callable, str]]] = <function relu at 0x7fc42a5c9280>, n_classes: int = 2, residual: bool = False, **kwargs) -> None
 |  
 |  A fully connected network for multitask classification.
 |  
 |  This class provides lots of options for customizing aspects of the model: the
 |  number and widths of layers, the activation functions, regularization methods,
 |  etc.
 |  
 |  It optionally can compose the model from pre-activation residual blocks, as
 |  described in https://arxiv.org/abs/160

In [49]:
model = dc.models.MultitaskClassifier(n_tasks = 12, n_features = 1024, layer_sizes = [1000])


In [50]:
model.fit(train_dataset, nb_epoch = 10)

0.48193400700887046

In [52]:
metric = dc.metrics.Metric(dc.metrics.roc_auc_score, np.mean)

In [54]:
train_scores = model.evaluate(train_dataset, [metric], transformers)
test_scores = model.evaluate(test_dataset, [metric], transformers)

In [55]:
print (train_scores, test_scores)

{'mean-roc_auc_score': 0.9578008260735348} {'mean-roc_auc_score': 0.6835958012859433}
